name: React App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Create app
      run: npx create-react-app dummy-app
    
    - name: Build app
      run: |
        cd dummy-app
        export PUBLIC_URL=/actions-playground
        yarn test
        yarn build
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dummy-app/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
