name: React App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17
    
    - name: create-react-app
      run: |
        npx create-react-app react-app
        cd ./react-app && npm run build --if-present
#     - run: npm test
