name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container: node:latest
    
    services:
      mongodb:
        image: mongo
        ports: ['27017:27017']

    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Check NodeJS
        run: node --version

      - name: Install AVA
        run: npm i ava
      
      - name: Install mongodb
        run: npm i mongodb
      
      - name: Run tests
        run: npx ava
